package me.growapet.shop;
import me.growapet.GrowAPet;import me.growapet.models.PlayerData;import org.bukkit.Bukkit;import org.bukkit.entity.Player;import java.util.Set;import java.util.UUID;import java.util.concurrent.ConcurrentHashMap;
public final class ShopManager{
 private static final String GEAR_KEY="gear_tier",TOOL_KEY="tool_tier";private final GrowAPet plugin;private final Set<UUID>pending=ConcurrentHashMap.newKeySet();public ShopManager(GrowAPet plugin){this.plugin=plugin;}
 public void applyAll(PlayerData data){for(ShopUpgrade upgrade:ShopUpgrade.values())if(upgrade!=ShopUpgrade.COIN_BOOST&&upgrade!=ShopUpgrade.DAMAGE_BOOST)upgrade.apply(data,data.getShopLevel(upgrade.getId()));recompute(data);}
 private void recompute(PlayerData data){data.setCoinMultiplier(ShopUpgrade.COIN_BOOST.valueAtLevel(data.getShopLevel(ShopUpgrade.COIN_BOOST.getId()))+GearTier.cumulativeBonus(data.getShopLevel(GEAR_KEY)));data.setDamageMultiplier(ShopUpgrade.DAMAGE_BOOST.valueAtLevel(data.getShopLevel(ShopUpgrade.DAMAGE_BOOST.getId()))+ToolTier.cumulativeBonus(data.getShopLevel(TOOL_KEY)));}
 public boolean canAfford(PlayerData data,ShopUpgrade upgrade){long cost=upgrade.costForLevel(data.getShopLevel(upgrade.getId()));return upgrade.getCurrency()==ShopUpgrade.Currency.COINS?data.getCoins()>=cost:data.getGems()>=cost;}
 public boolean purchase(Player player,ShopUpgrade upgrade){PlayerData data=plugin.getPlayerManager().get(player);if(data==null||!data.tryLockEconomy())return false;if(!pending.add(player.getUniqueId())){data.unlockEconomy();return false;}int level=data.getShopLevel(upgrade.getId());if(level>=upgrade.getMaxLevel()){pending.remove(player.getUniqueId());data.unlockEconomy();player.sendMessage("§cThat upgrade is already maxed.");return false;}long cost=upgrade.costForLevel(level);boolean coins=upgrade.getCurrency()==ShopUpgrade.Currency.COINS;if(!(coins?data.removeCoins(cost):data.removeGems(cost))){pending.remove(player.getUniqueId());data.unlockEconomy();player.sendMessage("§cYou cannot afford that upgrade.");return false;}data.setShopLevel(upgrade.getId(),level+1);if(upgrade==ShopUpgrade.COIN_BOOST||upgrade==ShopUpgrade.DAMAGE_BOOST)recompute(data);else upgrade.apply(data,level+1);persist(player,data,"UPGRADE:"+upgrade.name(),coins?cost:0,coins?0:cost,()->{if(coins)data.addCoinsRaw(cost);else data.addGemsRaw(cost);data.setShopLevel(upgrade.getId(),level);applyAll(data);},"Purchased "+upgrade.getDisplayName()+" level "+(level+1));return true;}
 public int getGearTier(PlayerData data){return data.getShopLevel(GEAR_KEY);}public int getToolTier(PlayerData data){return data.getShopLevel(TOOL_KEY);}public boolean canAffordGear(PlayerData data,GearTier gear){return data.getCoins()>=gear.getCoinCost()&&data.getGems()>=gear.getGemCost();}public boolean canAffordTool(PlayerData data,ToolTier tool){return data.getCoins()>=tool.getCoinCost()&&data.getGems()>=tool.getGemCost();}
 public boolean purchaseGear(Player player,GearTier gear){PlayerData data=plugin.getPlayerManager().get(player);if(data==null||!data.tryLockEconomy())return false;if(!pending.add(player.getUniqueId())){data.unlockEconomy();return false;}int owned=getGearTier(data);if(gear.getTier()!=owned+1||!canAffordGear(data,gear)){pending.remove(player.getUniqueId());data.unlockEconomy();player.sendMessage("§cBuy the previous tier and check your balance.");return false;}data.removeCoins(gear.getCoinCost());data.removeGems(gear.getGemCost());data.setShopLevel(GEAR_KEY,gear.getTier());recompute(data);persist(player,data,"GEAR:"+gear.name(),gear.getCoinCost(),gear.getGemCost(),()->{data.addCoinsRaw(gear.getCoinCost());data.addGemsRaw(gear.getGemCost());data.setShopLevel(GEAR_KEY,owned);recompute(data);},"Purchased "+gear.getDisplayName());return true;}
 public boolean purchaseTool(Player player,ToolTier tool){PlayerData data=plugin.getPlayerManager().get(player);if(data==null||!data.tryLockEconomy())return false;if(!pending.add(player.getUniqueId())){data.unlockEconomy();return false;}int owned=getToolTier(data);if(tool.getTier()!=owned+1||!canAffordTool(data,tool)){pending.remove(player.getUniqueId());data.unlockEconomy();player.sendMessage("§cBuy the previous tier and check your balance.");return false;}data.removeCoins(tool.getCoinCost());data.removeGems(tool.getGemCost());data.setShopLevel(TOOL_KEY,tool.getTier());recompute(data);persist(player,data,"TOOL:"+tool.name(),tool.getCoinCost(),tool.getGemCost(),()->{data.addCoinsRaw(tool.getCoinCost());data.addGemsRaw(tool.getGemCost());data.setShopLevel(TOOL_KEY,owned);recompute(data);},"Purchased "+tool.getDisplayName());return true;}
 private void persist(Player player,PlayerData data,String kind,long coins,long gems,Runnable rollback,String success){UUID id=player.getUniqueId();plugin.getPlayerManager().saveTransaction(data,UUID.randomUUID().toString(),kind,-coins,-gems,0).whenComplete((ignored,error)->Bukkit.getScheduler().runTask(plugin,()->{pending.remove(id);data.unlockEconomy();if(error!=null){rollback.run();if(player.isOnline())player.sendMessage("§cPurchase failed safely; your balance was restored.");return;}if(player.isOnline())player.sendMessage("§a"+success+"§a!");}));}
}
