package me.growapet.commands;

import me.growapet.GrowAPet;import me.growapet.leaderboards.LeaderboardType;import me.growapet.utils.Messages;import org.bukkit.command.*;import org.bukkit.entity.Player;import java.util.Locale;
public final class LeaderboardCommand implements CommandExecutor{
 private final GrowAPet plugin;public LeaderboardCommand(GrowAPet plugin){this.plugin=plugin;}
 @Override public boolean onCommand(CommandSender sender,Command command,String label,String[]args){String sub=args.length==0?"":args[0].toLowerCase(Locale.ROOT);if(isAdminSub(sub)){if(!sender.hasPermission("growapet.admin.leaderboards")){Messages.send(sender,"<red>ɪɴᴠᴀɪʟᴅ ᴄᴏᴍᴍᴀɴᴅ</red>");return true;}return admin(sender,args);}if(!(sender instanceof Player player)){Messages.send(sender,"<red>Players only. Use an admin leaderboard subcommand from console.</red>");return true;}LeaderboardType type=args.length==0?LeaderboardType.COINS:LeaderboardType.from(args[0]);if(type==null){Messages.send(player,"<red>Unknown leaderboard type.</red>");return true;}plugin.getLeaderboardManager().showPersonal(player,type);return true;}
 private boolean admin(CommandSender sender,String[]args){switch(args[0].toLowerCase(Locale.ROOT)){case"create"->{if(!(sender instanceof Player player)||args.length<3){Messages.send(sender,"<yellow>Usage: /leaderboard create <type> <id></yellow>");return true;}LeaderboardType type=LeaderboardType.from(args[1]);boolean made=plugin.getLeaderboardManager().create(args[2].toLowerCase(Locale.ROOT),type,player.getLocation());Messages.send(sender,made?"<green>Leaderboard created.</green>":"<red>Unable to create that leaderboard.</red>");}case"remove"->{boolean removed=args.length>=2&&plugin.getLeaderboardManager().remove(args[1].toLowerCase(Locale.ROOT));Messages.send(sender,removed?"<green>Leaderboard removed.</green>":"<red>Unknown leaderboard.</red>");}case"movehere"->{boolean moved=sender instanceof Player player&&args.length>=2&&plugin.getLeaderboardManager().move(args[1].toLowerCase(Locale.ROOT),player.getLocation());Messages.send(sender,moved?"<green>Leaderboard moved.</green>":"<red>Unable to move that leaderboard.</red>");}case"refresh"->{plugin.getLeaderboardManager().refreshAll();Messages.send(sender,"<green>Leaderboard refresh queued.</green>");}case"reload"->{plugin.getLeaderboardManager().reload();Messages.send(sender,"<green>Leaderboard configuration reloaded.</green>");}case"list"->Messages.send(sender,"<aqua>Leaderboards</aqua> <dark_gray>•</dark_gray> <white><ids></white>",Messages.value("ids",String.join(", ",plugin.getLeaderboardManager().ids())));default->{}}return true;}
 private static boolean isAdminSub(String sub){return java.util.Set.of("create","remove","movehere","refresh","reload","list").contains(sub);}
}
