package me.growapet.commands;

import me.growapet.GrowAPet;import me.growapet.utils.Messages;import org.bukkit.Bukkit;import org.bukkit.command.*;import org.bukkit.entity.Player;import java.util.Locale;import java.util.UUID;
public final class TradeCommand implements CommandExecutor{
 private final GrowAPet plugin;public TradeCommand(GrowAPet plugin){this.plugin=plugin;}
 @Override public boolean onCommand(CommandSender sender,Command command,String label,String[]args){if(!(sender instanceof Player player)){Messages.send(sender,"<red>Players only.</red>");return true;}if(args.length==0){usage(player);return true;}try{switch(args[0].toLowerCase(Locale.ROOT)){case"accept"->{require(args,1);plugin.getTradeManager().accept(player);}case"confirm"->{require(args,1);plugin.getTradeManager().confirm(player);}case"cancel"->{require(args,1);plugin.getTradeManager().cancel(player.getUniqueId(),"Trade cancelled.");}case"offer"->{if(args.length<2)throw new IllegalArgumentException();switch(args[1].toLowerCase(Locale.ROOT)){case"coins"->{require(args,3);plugin.getTradeManager().offerCurrency(player,true,positive(args[2]));}case"gems"->{require(args,3);plugin.getTradeManager().offerCurrency(player,false,positive(args[2]));}case"pet"->{require(args,3);plugin.getTradeManager().offerPet(player,UUID.fromString(args[2]));}case"egg"->{require(args,2);plugin.getTradeManager().offerEgg(player);}default->throw new IllegalArgumentException();}}default->{require(args,1);Player target=Bukkit.getPlayerExact(args[0]);if(target==null)Messages.send(player,"<red>That player is not online.</red>");else plugin.getTradeManager().request(player,target);}}}catch(IllegalArgumentException error){Messages.send(player,"<red>Invalid trade command or amount.</red>");usage(player);}return true;}
 private static void usage(Player player){Messages.send(player,"<aqua><bold>TRADING</bold></aqua>");Messages.send(player,"<gray>• Request → <white>/trade ‹player›</white></gray>");Messages.send(player,"<gray>• Offer → <white>/trade offer ‹coins|gems|pet|egg› [value]</white></gray>");Messages.send(player,"<gray>• Finish → <white>/trade confirm</white> <dark_gray>•</dark_gray> <white>/trade cancel</white></gray>");}
 private static void require(String[]args,int length){if(args.length!=length)throw new IllegalArgumentException();}private static long positive(String value){long parsed=Long.parseLong(value);if(parsed<0)throw new IllegalArgumentException();return parsed;}
}
