package me.growapet.gui;

import me.growapet.GrowAPet;import me.growapet.leaderboards.LeaderboardManager;import me.growapet.leaderboards.LeaderboardType;import me.growapet.utils.Messages;import org.bukkit.Bukkit;import org.bukkit.Material;import org.bukkit.entity.Player;import org.bukkit.inventory.ItemStack;import java.util.*;
public final class LeaderboardMenu extends Menu{
 private static final int[]ROWS={27,28,29,30,31,32,33,34,35,40};private final GrowAPet plugin;private LeaderboardType type;private List<LeaderboardManager.Entry>entries=List.of();private boolean loading=true;
 public LeaderboardMenu(GrowAPet plugin,Player viewer,LeaderboardType type){super(viewer,Messages.parse("<aqua><bold>LEADERBOARDS</bold></aqua>"),54);this.plugin=plugin;this.type=type;}
 @Override public void build(){fill();LeaderboardType[]types=LeaderboardType.values();for(int i=0;i<types.length;i++){LeaderboardType candidate=types[i];setItem(i,item(candidate.icon(),(candidate==type?"<aqua>":"<white>")+"<bold>"+candidate.label().toUpperCase(Locale.ROOT)+"</bold>"+(candidate==type?"</aqua>":"</white>"),List.of("<gray>• Click → view rankings</gray>")),event->{type=candidate;load();});}setItem(22,item(type.icon(),"<aqua><bold>"+type.label().toUpperCase(Locale.ROOT)+"</bold></aqua>",List.of("<gray>• Live and persisted player data</gray>","<gray>• Updates when refreshed</gray>")),null);if(loading)setItem(31,item(Material.CLOCK,"<yellow><bold>LOADING</bold></yellow>",List.of("<gray>Fetching current rankings…</gray>")),null);else for(int i=0;i<ROWS.length;i++){if(i>=entries.size())setItem(ROWS[i],item(Material.GRAY_DYE,"<dark_gray>#"+(i+1)+" • Unranked</dark_gray>",List.of()),null);else{LeaderboardManager.Entry entry=entries.get(i);String color=switch(i){case 0->"<gold>";case 1->"<gray>";case 2->"<yellow>";default->"<white>";};setItem(ROWS[i],item(i<3?Material.PLAYER_HEAD:Material.PAPER,color+"<bold>#"+(i+1)+" • "+safe(entry.name())+"</bold>"+color.replace("<","</"),List.of("<gray>• "+type.label()+" → <white>"+LeaderboardManager.format(type,entry.value())+"</white></gray>")),null);}}setItem(45,item(Material.BARRIER,"<red><bold>BACK</bold></red>",List.of("<gray>• Click → close this menu</gray>")),event->viewer.closeInventory());setItem(49,item(Material.COMPASS,"<aqua><bold>REFRESH</bold></aqua>",List.of("<gray>• Click → refresh rankings</gray>")),event->load());}
 @Override public void open(){super.open();load();}
 private void load(){loading=true;if(getInventory()!=null)refresh();plugin.getLeaderboardManager().top(type,10).whenComplete((result,error)->Bukkit.getScheduler().runTask(plugin,()->{if(!isActive())return;entries=error==null?result:List.of();loading=false;refresh();}));}
 private void fill(){ItemStack pane=item(Material.GRAY_STAINED_GLASS_PANE," ",List.of());for(int i=0;i<54;i++)setItem(i,pane,null);}private static ItemStack item(Material material,String name,List<String>lore){return new ItemBuilder(material).name(Messages.parse(name)).loreComponents(lore.stream().map(Messages::parse).toList()).build();}private static String safe(String value){return value.replace("<","‹").replace(">","›");}
}
