package me.growapet.gui;

import me.growapet.GrowAPet;import me.growapet.models.PlayerData;import me.growapet.store.StoreOffer;import me.growapet.utils.Messages;import org.bukkit.Material;import org.bukkit.entity.Player;import org.bukkit.inventory.ItemStack;import java.text.NumberFormat;import java.util.List;import java.util.Locale;
public final class StoreMenu extends Menu{
 private static final NumberFormat NUMBER=NumberFormat.getIntegerInstance(Locale.US);private final GrowAPet plugin;
 public StoreMenu(GrowAPet plugin,Player viewer){super(viewer,Messages.parse(plugin.getConfigManager().store().getString("title","<light_purple><bold>CREDIT STORE</bold></light_purple>")),validSize(plugin.getConfigManager().store().getInt("size",54)));this.plugin=plugin;}
 @Override public void build(){fill();PlayerData data=plugin.getPlayerManager().get(viewer);if(data==null)return;setItem(4,item(Material.NETHER_STAR,"<light_purple><bold>YOUR CREDITS</bold></light_purple>",List.of("<gray>• Balance → <white>"+NUMBER.format(data.getCredits())+"</white></gray>","","<gray>Permanent offers can only be purchased once.</gray>")),null);for(StoreOffer offer:plugin.getStoreManager().offers()){if(offer.slot()<0||offer.slot()>=getInventory().getSize())continue;boolean owned=plugin.getStoreManager().owns(viewer.getUniqueId(),offer),afford=plugin.getStoreManager().canAfford(data,offer);String color=owned?"<green>":afford?"<yellow>":"<red>",close=color.replace("<","</");List<String>lore=List.of("<gray>• Reward → <white>"+safe(offer.description())+"</white></gray>","<gray>• Price → <light_purple>"+NUMBER.format(offer.creditPrice())+" Credits</light_purple></gray>","",owned?"<green>Already owned</green>":afford?"<green>Click → purchase</green>":"<red>You need more Credits.</red>");setItem(offer.slot(),item(offer.icon(),color+"<bold>"+safe(offer.displayName())+"</bold>"+close,lore),owned||!afford?null:event->{if(plugin.getStoreManager().purchase(viewer,offer))refresh();});}setItem(getInventory().getSize()-5,item(Material.BARRIER,"<red><bold>CLOSE</bold></red>",List.of("<gray>• Click → close this menu</gray>")),event->viewer.closeInventory());}
 private void fill(){ItemStack pane=item(Material.GRAY_STAINED_GLASS_PANE," ",List.of());for(int i=0;i<getInventory().getSize();i++)setItem(i,pane,null);}private static ItemStack item(Material material,String name,List<String>lore){return new ItemBuilder(material).name(Messages.parse(name)).loreComponents(lore.stream().map(Messages::parse).toList()).build();}private static int validSize(int value){return value>=9&&value<=54&&value%9==0?value:54;}private static String safe(String value){return value==null?"":value.replace("<","‹").replace(">","›");}
}
