package me.growapet.settings;
import me.growapet.GrowAPet;import java.sql.*;import java.util.*;import java.util.concurrent.*;
public final class OptionsManager{
 private final GrowAPet plugin;private final Map<UUID,Map<String,String>>values=new ConcurrentHashMap<>();private final Set<UUID>loaded=ConcurrentHashMap.newKeySet();public OptionsManager(GrowAPet p){plugin=p;}
 public CompletableFuture<Void>load(UUID id){loaded.remove(id);return plugin.getDatabase().async(c->{Map<String,String>result=new ConcurrentHashMap<>();try(PreparedStatement s=c.prepareStatement("SELECT setting_key,setting_value FROM settings WHERE player_uuid=?")){s.setString(1,id.toString());try(ResultSet r=s.executeQuery()){while(r.next())result.put(r.getString(1),r.getString(2));}}return result;}).thenAccept(result->{values.merge(id,result,(existing,fromDatabase)->{fromDatabase.putAll(existing);return fromDatabase;});loaded.add(id);});}
 public boolean enabled(UUID id,String key,boolean fallback){return Boolean.parseBoolean(values.getOrDefault(id,Map.of()).getOrDefault(key,String.valueOf(fallback)));}public String get(UUID id,String key,String fallback){return values.getOrDefault(id,Map.of()).getOrDefault(key,fallback);}
 public CompletableFuture<Void>set(UUID id,String key,String value){Map<String,String>playerValues=values.computeIfAbsent(id,k->new ConcurrentHashMap<>());String previous=playerValues.put(key,value);return plugin.getDatabase().<Void>async(c->{try(PreparedStatement s=c.prepareStatement("INSERT INTO settings(player_uuid,setting_key,setting_value)VALUES(?,?,?) ON CONFLICT(player_uuid,setting_key)DO UPDATE SET setting_value=excluded.setting_value")){s.setString(1,id.toString());s.setString(2,key);s.setString(3,value);s.executeUpdate();}return null;}).whenComplete((ignored,error)->{if(error==null)return;if(previous==null)playerValues.remove(key,value);else playerValues.replace(key,value,previous);plugin.getLogger().severe("Failed to persist setting "+key+" for "+id+": "+error.getMessage());});}
 public boolean isLoaded(UUID id){return loaded.contains(id);}
 public void cache(UUID id,String key,String value){values.computeIfAbsent(id,k->new ConcurrentHashMap<>()).put(key,value);}
 public void unload(UUID id){loaded.remove(id);values.remove(id);}
}
